public enum Data_Names {
    //  work class
    PRIVATE, SELF_EMP_NOT_INC, SELF_EMP_INC, FEDERAL_GOV, LOCAL_GOV, STATE_GOV, WITHOUT_PAY, NEVER_WORKED,
    // education
    BACHELORS, SOME_COLLEGE, _11TH, HS_GRAD, PROF_SCHOOL, ASSOC_ACDM, ASSOC_VOC, NINTH, _7_8TH, _12TH, MASTERS, _1ST_4TH, _10TH, DOCTORATE, _5TH_6TH, PRESCHOOL,
    // marital_status
    MARRIED_CIV_SPOUSE, DIVORCED, NEVER_MARRIED, SEPARATED, WIDOWED, MARRIED_SPOUSE_ABSENT, MARRIED_AF_SPOUSE,
    // occupation
    TECH_SUPPORT, CRAFT_REPAIR, OTHER_SERVICE, SALES, EXEC_MANAGERIAL, PROF_SPECIALTY, HANDLERS_CLEANERS, MACHINE_OP_INSPCT, ADM_CLERICAL, FARMING_FISHING, TRANSPORT_MOVING, PRIV_HOUSE_SERV, PROTECTIVE_SERV, ARMED_FORCES,
    // RELATIONSHIP
    WIFE, OWN_CHILD, HUSBAND, NOT_IN_FAMILY, OTHER_RELATIVE, UNMARRIED,
    // RACE
    WHITE, ASIAN_PAC_ISLANDER, AMER_INDIAN_ESKIMO, OTHER, BLACK,
    // SEX
    FEMALE, MALE,
    // NATIVE COUNTRY
    UNITED_STATES, CAMBODIA, ENGLAND, PUERTO_RICO, CANADA, GERMANY, OUTLYING_US, INDIA, JAPAN, GREECE, SOUTH, CHINA, CUBA, IRAN, HONDURAS, PHILIPPINES, ITALY, POLAND, JAMAICA, VIETNAM, MEXICO, PORTUGAL, IRELAND, FRANCE, DOMINICAN_REPUBLIC, LAOS, ECUADOR, TAIWAN, HAITI, COLUMBIA, HUNGARY, GUATEMALA, NICARAGUA, SCOTLAND, THAILAND, YUGOSLAVIA, EL_SALVADOR, TRINADAD_TOBAGO, PERU, HONG, HOLAND_NETHERLANDS,

}
